name: CI/CD workflow

on: workflow_dispatch

env:
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: 'mlops-agh/lab11'
  S3_BUCKET: 'mlops-lab11-models-pk'

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Run ruff check
        uses: astral-sh/ruff-action@v3

      - name: Run pytest
        run: pytest tests/
